#
# Copyright 2013-2026 chronicle.software; SPDX-License-Identifier: Apache-2.0
#

# Tracing if resources are closed/released correctly.
jvm.resource.tracing=true
# for profiling
jvm.safepoint.enabled=false
# reduce logging of the announcer
chronicle.announcer.disable=true